AY2122S2-CS2103-W17-1/tp

src/main/java/seedu/contax/ui/ListContentType.java, src/main/java/seedu/contax/ui/MainWindow.java, src/main/resources/view/MainWindow.fxml
This is a minor skeletal change to the UI to prepare it for displaying other types of models in its list window.
None, this is a minor refactoring change.
=> Extend UI to Allow Displaying Other Types of  Models

src/main/java/seedu/contax/model/IndexedCsvFile.java, src/test/java/seedu/contax/logic/commands/ImportCsvCommandTest.java, src/test/java/seedu/contax/model/IndexedCsvFileTest.java
This PR adds the equals test for the `IndexedCsvFile` model and the `ImportCsvCommand` command. Was supposed to be in #132 but I forgot to add it 
Related PR: #132 
Related Issue: #92
=> Import CSV - Equals test for Command and Model

src/main/java/seedu/contax/model/ModelManager.java, src/test/java/seedu/contax/model/ModelManagerTest.java
This PR directly addresses bug #151 that results in an inconsistent model state by asserting model consistency at the ModelManager level. Tests were also added to verify that the cascading modifications and delete work as intended.
- Closes #151
=> Add Cascading Delete and Update for Persons

src/main/java/seedu/contax/ui/onboarding/OnboardingInstruction.java, src/main/java/seedu/contax/ui/onboarding/OnboardingWindow.java, src/main/resources/view/onboarding/OnboardingInstruction.fxml
This PR fixes the bug which causes the instruction display message to be cut off.
- closes #148
=> Small fix for onboarding instruction label

src/main/java/seedu/contax/commons/core/GuiListContentType.java, src/main/java/seedu/contax/logic/commands/CommandResult.java, src/main/java/seedu/contax/logic/commands/FindCommand.java, src/main/java/seedu/contax/logic/commands/ListAppointmentCommand.java, src/main/java/seedu/contax/logic/commands/ListCommand.java, src/main/java/seedu/contax/logic/commands/ListTagCommand.java, src/main/java/seedu/contax/ui/MainWindow.java, src/test/java/seedu/contax/logic/commands/ChainCommandTest.java, src/test/java/seedu/contax/logic/commands/CommandResultTest.java, src/test/java/seedu/contax/logic/commands/FindCommandTest.java, src/test/java/seedu/contax/logic/commands/ListAppointmentCommandTest.java, src/test/java/seedu/contax/logic/commands/ListCommandTest.java, src/test/java/seedu/contax/logic/commands/ListTagCommandTest.java
This PR refactors the `ListContentType` enum into the commons package to better reflect its usage in both the Logic component and the GUI component. It is also renamed to `GuiListContentType` to better indicate its purpose.
- None
=> Refactor ListContentType to Commons Package

src/main/java/seedu/contax/logic/commands/DeleteTagCommand.java, src/main/java/seedu/contax/logic/parser/AddressBookParser.java, src/main/java/seedu/contax/model/AddressBook.java, src/main/java/seedu/contax/model/Model.java, src/main/java/seedu/contax/model/ModelManager.java, src/main/java/seedu/contax/model/person/Person.java, src/main/java/seedu/contax/model/tag/UniqueTagList.java, src/test/java/seedu/contax/logic/commands/AddAppointmentCommandTest.java, src/test/java/seedu/contax/logic/commands/AddCommandTest.java, src/test/java/seedu/contax/logic/commands/AddTagCommandTest.java, src/test/java/seedu/contax/logic/commands/DeleteTagCommandTest.java, src/test/java/seedu/contax/logic/commands/ImportCsvCommandTest.java, src/test/java/seedu/contax/logic/parser/AddressBookParserTest.java, src/test/java/seedu/contax/model/AddressBookTest.java, src/test/java/seedu/contax/model/ModelManagerTest.java, src/test/java/seedu/contax/model/person/PersonTest.java, src/test/java/seedu/contax/model/tag/UniqueTagListTest.java
This PR provides tighter integrity enforcement in the Person-Tag relationship by moving the synchronisation logic from the `Logic` component to the `Model` component. 
- Fixes #160
=> Fix - Person-Tag Integrity Enforcement

src/main/java/seedu/contax/logic/Logic.java, src/main/java/seedu/contax/logic/LogicManager.java, src/main/java/seedu/contax/model/appointment/Appointment.java, src/main/java/seedu/contax/model/appointment/DisjointAppointmentList.java, src/main/java/seedu/contax/model/appointment/StartDateTime.java, src/main/java/seedu/contax/ui/AppointmentCard.java, src/main/java/seedu/contax/ui/MainWindow.java, src/main/java/seedu/contax/ui/StatusBarFooter.java, src/main/resources/view/AppointmentListCard.fxml, src/test/java/seedu/contax/logic/LogicManagerTest.java, src/test/java/seedu/contax/model/ModelManagerTest.java, src/test/java/seedu/contax/model/appointment/AppointmentTest.java, src/test/java/seedu/contax/model/appointment/DisjointAppointmentListTest.java, src/test/java/seedu/contax/model/appointment/StartDateTimeTest.java
This PR modifies the `DisjointAppointmentList` class to maintain a chronological ordering for appointments, and should seamlessly propagate to all components in the schedule subsystem that depend on it.
- Test Cases not written to take chronological ordering into account might fail after this PR is merged
- Closes #167
=> Add Chronological Ordering for Appointments

src/main/java/seedu/contax/model/ModelManager.java, src/test/java/seedu/contax/model/ModelManagerTest.java
This PR directly addresses issue #190, which was caused by the appointments cascading functionality in `ModelManager`. Test cases were also updated to pick up the issue to ensure that it does not occur.
- Closes #190
=> Fix NullPointerException in ModelManager

src/main/java/seedu/contax/storage/JsonSerializableSchedule.java, src/test/data/JsonScheduleStorageTest/overlappingAppointmentSchedule.json, src/test/data/JsonSerializableScheduleTest/invalidAppointmentSchedule.json, src/test/java/seedu/contax/storage/JsonScheduleStorageTest.java, src/test/java/seedu/contax/storage/JsonSerializableScheduleTest.java
This is a minor PR fix to allow valid appointments to be loaded even if there exists some invalid appointments in the data file. Test cases were updated to reflect this change.
- Closes #195
=> Change Schedule Inflation to be More Forgiving

docs/UserGuide.md, src/main/java/seedu/contax/commons/util/DateUtil.java, src/main/java/seedu/contax/commons/util/datetimeparser/DateParser.java, src/main/java/seedu/contax/commons/util/datetimeparser/DateParserPatternProvider.java, src/main/java/seedu/contax/commons/util/datetimeparser/TimeParser.java, src/main/java/seedu/contax/commons/util/datetimeparser/TimeParserPatternProvider.java, src/test/java/seedu/contax/commons/util/DateUtilTest.java, src/test/java/seedu/contax/commons/util/datetimeparser/DateParserTest.java, src/test/java/seedu/contax/commons/util/datetimeparser/TimeParserTest.java, src/test/java/seedu/contax/testutil/DateInputUtil.java
This PR adds the support for accepting natural date and time input formats. In particular, the new input parser allows:
- Using / as a delimiter for dates: `30/12/2022`
- Textual Months: `20 Dec 2023`, `20 november 2020`
- 12-hour Time: `11:30 PM`
See the updated UG for more details.
- Closes #197
=> Feature - Add Natural Date and Time Parsing

build.gradle
This PR enables assertions in the gradle build file, per the requirements in the weekly tasks.
- None, this is a chore.
=> Enable Assertions for Run Task

src/main/java/seedu/contax/MainApp.java
This PR bumps the internal version number to v1.2.1 for the trial release required for Week 10 milestones.
=> Version Bump - 1.2.1

src/main/java/seedu/contax/logic/commands/RangeCommand.java, src/main/java/seedu/contax/logic/parser/ParserUtil.java, src/main/java/seedu/contax/logic/parser/RangeCommandParser.java, src/test/java/seedu/contax/logic/parser/ParserUtilTest.java
This PR correct the range command that support reorder `from/` `to/`
=> Bug fix for range support reordering

src/main/java/seedu/contax/logic/commands/FreeBetweenCommand.java, src/main/java/seedu/contax/model/AppointmentSlotList.java, src/main/java/seedu/contax/model/Model.java, src/main/java/seedu/contax/model/ModelManager.java, src/test/java/seedu/contax/logic/commands/AddAppointmentCommandTest.java, src/test/java/seedu/contax/logic/commands/AddPersonCommandTest.java, src/test/java/seedu/contax/logic/commands/AddTagCommandTest.java, src/test/java/seedu/contax/logic/commands/RangeCommandTest.java, src/test/java/seedu/contax/model/AppointmentSlotListTest.java, src/test/java/seedu/contax/model/ModelManagerTest.java, src/test/java/seedu/contax/model/appointment/AppointmentSlotTest.java
This PR is a bugfix that directly addresses the issue #239. It changes how the flow of displaying empty slots in the schedule is handled, and solves the problem of slots not combining.
- Closes #239
=> Fix Free Slot Display Update

docs/UserGuide.md, src/main/java/seedu/contax/logic/commands/AddAppointmentCommand.java, src/main/java/seedu/contax/logic/commands/AppointmentsBetweenCommand.java, src/main/java/seedu/contax/logic/commands/DeleteAppointmentCommand.java, src/main/java/seedu/contax/logic/commands/EditAppointmentCommand.java, src/main/java/seedu/contax/logic/commands/FindAppointmentCommand.java, src/main/java/seedu/contax/logic/commands/ListAppointmentCommand.java, src/main/java/seedu/contax/model/appointment/Appointment.java, src/main/java/seedu/contax/model/appointment/Priority.java, src/main/java/seedu/contax/storage/JsonAdaptedAppointment.java, src/main/java/seedu/contax/ui/appointment/cardfactory/AppointmentCard.java, src/main/resources/view/AppointmentListCard.fxml, src/main/resources/view/DarkTheme.css, src/main/resources/view/Extensions.css, src/test/java/seedu/contax/model/appointment/PriorityTest.java
This PR renames all the appointment commands to shorten the command word. It also refines the structure of the appointment priority, and streamlines the UI to be more consistent with the current look-and-feel.
- Closes #257
=> Refactor - Change Command Names and Improve Priority Enum Structure

src/main/java/seedu/contax/storage/JsonAdaptedPerson.java, src/main/java/seedu/contax/storage/JsonAddressBookStorage.java, src/main/java/seedu/contax/storage/JsonSerializableAddressBook.java, src/test/java/seedu/contax/storage/JsonAddressBookStorageTest.java, src/test/java/seedu/contax/storage/JsonSerializableAddressBookTest.java
This PR is to change the person parsing from `.json` to be more forgiving, such that it skips invalid Persons only instead of loading an entirely new AddressBook.
Same fix applied for tags, and relevant tests are modified to reflect this
This closes #253
=> Improvement - Adjust json parsing to be forgiving

src/main/java/seedu/contax/model/CompositeObservableList.java
This is a workaround for the bug observed in issue #249. A try catch is used because it does not affect the result or correctness of the logic.
- Closes #249
=> Bug Fix - Hotfix for Composite Observable List Bug

docs/DeveloperGuide.md
Since UC18 is a bit minor and we decided to leave it out, this PR just bumps the UC numbers down
=> Bump test case numbers down

src/main/java/seedu/contax/model/person/Phone.java
This PR changes the `Phone` regex checker to allow phone numbers starting with 0
This closes #287
=> Bugfix - Phone number not allowing numbers starting with 0

docs/UserGuide.md
This PR resolves #313. It's some random markdown quirk where theres a space in front of the backtick.
If we want to show how the space at the front will also be trimmed, one possibility is to show 2 separate examples, or escape the spaces (?)
=> Small UG formatting fix

src/main/java/seedu/contax/model/AddressBook.java, src/test/java/seedu/contax/model/AddressBookTest.java, src/test/java/seedu/contax/model/appointment/NameTest.java, src/test/java/seedu/contax/model/person/AddressTest.java, src/test/java/seedu/contax/model/person/EmailTest.java, src/test/java/seedu/contax/model/person/PhoneTest.java, src/test/java/seedu/contax/model/person/UniquePersonListTest.java, src/test/java/seedu/contax/model/tag/TagTest.java, src/test/java/seedu/contax/model/tag/UniqueTagListTest.java
This PR adds defense mechanisms relating to `AddressBook#resetData()` and adds test cases (equality check in particular) for existing model classes.
None.
=> Fix - Reset mechanism in Address Book

src/main/java/seedu/contax/model/ModelManager.java, src/test/java/seedu/contax/model/ModelManagerTest.java
This PR fixes a potential gap in model consistency similar to
- #334
but at the `Model` level for `Schedule` and `AddressBook` synchronization.
- None
=> Fix - Potential Inconsistent Model State

docs/UserGuide.md, src/main/java/seedu/contax/logic/commands/BatchCommand.java, src/main/java/seedu/contax/logic/commands/RangeCommand.java
This PR fixes the fact that `batch` and `range` do not reject the commands that should be rejected according to the user guide.
- None, but this is a urgent fix.
=> Fix Obvious Issues With Batch and Range

src/main/java/seedu/contax/ui/PersonCard.java, src/main/resources/view/PersonListCard.fxml
If you currently attempt to perform `deleteperson 4` on a list with 4 persons, the row height jumps after you delete, which is not intended.
This change hardcodes a width for tag labels to solve this issue.
=> Fix Urgent Visual Bug with Random Person Row Heights
