- docs/_config.yml
- docs/_sass/minima/_base.scss
This PR updates the configuration files for Jekyll to reflect that the forked project is now ContaX instead of AB-3.
It completes task #58.
> Update Jekyll Site-Wide Settings

- docs/UserGuide.md
This PR removes the original AB3 description from the User Guide and replaces it with an appropriate description for ContaX.
* #75
> Update Overall User Guide Description

- docs/DeveloperGuide.md
This PR updates only the use cases in Developer Guide.
A staging version of the updated Developer Guide can be found [here](https://wei-xinn.github.io/tp/DeveloperGuide.html#use-cases).
* #63
> Add use cases for DeveloperGuide

- docs/UserGuide.md
This PR attempts to remove traces of the AB3 project from the user guide.
None, this is a hotfix for the previous PR #76.
> Remove Hyperlink to AB3 Github Page

- docs/DeveloperGuide.md
This PR adds Non-Functional Requirements (NFRs) to the developer guide. No other files are changed.
* #64
> Add Non-Functional Requirements to Developer Guide

- docs/UserGuide.md
* Improves standardization of language and formatting across user guide
* Follows up on #89
> Improve Quality of User Guide

- src/main/java/seedu/contax/logic/Logic.java
- src/main/java/seedu/contax/logic/LogicManager.java
- src/main/java/seedu/contax/logic/commands/CommandResult.java
- src/main/java/seedu/contax/logic/commands/ExitCommand.java
- src/main/java/seedu/contax/logic/commands/FindCommand.java
- src/main/java/seedu/contax/logic/commands/HelpCommand.java
- src/main/java/seedu/contax/logic/commands/ListAppointmentCommand.java
- src/main/java/seedu/contax/logic/commands/ListCommand.java
- src/main/java/seedu/contax/logic/parser/AddressBookParser.java
- src/main/java/seedu/contax/ui/AppointmentCard.java
- src/main/java/seedu/contax/ui/AppointmentListPanel.java
- src/main/java/seedu/contax/ui/ListContentType.java
- src/main/java/seedu/contax/ui/MainWindow.java
- src/main/resources/view/AppointmentListCard.fxml
- src/main/resources/view/AppointmentListPanel.fxml
- src/main/resources/view/DarkTheme.css
- src/test/java/seedu/contax/logic/LogicManagerTest.java
- src/test/java/seedu/contax/logic/commands/CommandResultTest.java
- src/test/java/seedu/contax/logic/commands/FindCommandTest.java
- src/test/java/seedu/contax/logic/commands/ListAppointmentCommandTest.java
- src/test/java/seedu/contax/logic/commands/ListCommandTest.java
- src/test/java/seedu/contax/logic/parser/AddressBookParserTest.java
- src/test/java/seedu/contax/testutil/AppointmentUtil.java
This PR adds a functionality to list the appointments currently in the system.
- Please merge PR #133 before merging this because it builds on top of the skeleton in that PR.
- Closes #108
> Feature - Add Appointment Listing

- src/main/java/seedu/contax/logic/Logic.java
- src/main/java/seedu/contax/logic/LogicManager.java
- src/main/java/seedu/contax/logic/commands/AddTagCommand.java
- src/main/java/seedu/contax/logic/commands/ListTagCommand.java
- src/main/java/seedu/contax/logic/parser/AddTagCommandParser.java
- src/main/java/seedu/contax/logic/parser/AddressBookParser.java
- src/main/java/seedu/contax/model/Model.java
- src/main/java/seedu/contax/model/ModelManager.java
- src/main/java/seedu/contax/model/tag/UniqueTagList.java
- src/main/java/seedu/contax/model/tag/exceptions/DuplicateTagException.java
- src/main/java/seedu/contax/ui/ListContentType.java
- src/main/java/seedu/contax/ui/MainWindow.java
- src/main/java/seedu/contax/ui/TagCard.java
- src/main/java/seedu/contax/ui/TagListPanel.java
- src/main/resources/view/TagListCard.fxml
- src/main/resources/view/TagListPanel.fxml
- src/test/java/seedu/contax/logic/commands/AddAppointmentCommandTest.java
- src/test/java/seedu/contax/logic/commands/AddCommandTest.java
- src/test/java/seedu/contax/logic/commands/AddTagCommandTest.java
- src/test/java/seedu/contax/logic/commands/ListTagCommandTest.java
This PR adds a command where the user can list all tags that are stored in ContaX.
- Closes #127
> Feature - Listing Tags

- src/main/java/seedu/contax/ui/MainWindow.java
This is a bug introduced during merging, an extra line was accidentally merged.
**Severe**
None
> Fix Bug Where Persons List is Not Displayed

- src/main/java/seedu/contax/model/onboarding/OnboardingStep.java
- src/main/java/seedu/contax/model/onboarding/OnboardingStory.java
- src/main/java/seedu/contax/ui/onboarding/OnboardingStoryManager.java
- src/main/java/seedu/contax/ui/onboarding/OnboardingWindow.java
- src/main/java/seedu/contax/ui/onboarding/Overlay.java
- src/main/resources/view/DarkTheme.css
- src/main/resources/view/onboarding/Overlay.fxml
- src/test/java/seedu/contax/model/OnboardingStepTest.java
- src/test/java/seedu/contax/model/OnboardingStoryTest.java
This PR addresses the following issues
- Move onboarding models to separate package
- Remove unnecessary overlays
- Add missing colon in DarkTheme.css
> Small fixes for onboarding guide feature

- src/main/java/seedu/contax/model/AddressBook.java
- src/main/java/seedu/contax/model/onboarding/OnboardingStep.java
- src/test/java/seedu/contax/model/AddressBookTest.java
- src/test/java/seedu/contax/model/ModelManagerTest.java
- src/test/java/seedu/contax/model/OnboardingStepTest.java
- src/test/java/seedu/contax/model/UserPrefsTest.java
- src/test/java/seedu/contax/model/appointment/AppointmentTest.java
- src/test/java/seedu/contax/model/person/UniquePersonListTest.java
This PR adds additional tests to improve the test coverage of the model package. It also fixes the equality check in `OnboardingStep`.
None, this is a test improvement.
> Improve Test Coverage in Model Package

- src/test/java/seedu/contax/logic/commands/ImportCsvCommandTest.java
This PR fixes the failing tests due to lack of proper tags after importing csv. Follow up from #159
> Fix test cases to add tag to expectedModel

- src/main/java/seedu/contax/logic/commands/ImportCsvCommand.java
- src/main/java/seedu/contax/storage/CsvManager.java
This PR is to abstract out the import csv logic over it's own standalone file, since logic shouldn't be inside the the command execute itself.
> Refactor import logic to standalone manager

- src/main/java/seedu/contax/commons/core/Messages.java
- src/main/java/seedu/contax/commons/util/DateUtil.java
- src/main/java/seedu/contax/logic/commands/AddAppointmentCommand.java
- src/main/java/seedu/contax/logic/commands/EditAppointmentCommand.java
- src/main/java/seedu/contax/logic/parser/AddressBookParser.java
- src/main/java/seedu/contax/logic/parser/EditAppointmentCommandParser.java
- src/main/java/seedu/contax/logic/parser/ParserUtil.java
- src/test/java/seedu/contax/commons/util/DateUtilTest.java
- src/test/java/seedu/contax/logic/commands/CommandTestUtil.java
- src/test/java/seedu/contax/logic/commands/EditAppointmentCommandTest.java
- src/test/java/seedu/contax/logic/parser/AddressBookParserTest.java
- src/test/java/seedu/contax/logic/parser/EditAppointmentCommandParserTest.java
- src/test/java/seedu/contax/testutil/AppointmentUtil.java
- src/test/java/seedu/contax/testutil/DateInputUtil.java
- src/test/java/seedu/contax/testutil/EditAppointmentDescriptorBuilder.java
This PR adds a command for modifying appointments previously created.
- Closes #114
> Feature - Add Appointment Modification

- src/main/java/seedu/contax/logic/commands/ImportCsvCommand.java
This PR removes some old redundant code as a result of #166. 
Functionality doesn't change because even with this code it will just do nothing but removing for tidiness
> Remove small redundant code

- src/main/java/seedu/contax/commons/util/DateUtil.java
- src/main/java/seedu/contax/logic/LogicManager.java
- src/main/java/seedu/contax/logic/commands/AppointmentsBetweenCommand.java
- src/main/java/seedu/contax/logic/commands/DeleteAppointmentCommand.java
- src/main/java/seedu/contax/logic/commands/EditAppointmentCommand.java
- src/main/java/seedu/contax/logic/commands/ListAppointmentCommand.java
- src/main/java/seedu/contax/logic/parser/AddressBookParser.java
- src/main/java/seedu/contax/logic/parser/AppointmentsBetweenCommandParser.java
- src/main/java/seedu/contax/logic/parser/CliSyntax.java
- src/main/java/seedu/contax/model/Model.java
- src/main/java/seedu/contax/model/ModelManager.java
- src/main/java/seedu/contax/model/appointment/DateRangePredicate.java
- src/test/java/seedu/contax/commons/util/DateUtilTest.java
- src/test/java/seedu/contax/logic/commands/AddAppointmentCommandTest.java
- src/test/java/seedu/contax/logic/commands/AddCommandTest.java
- src/test/java/seedu/contax/logic/commands/AddTagCommandTest.java
- src/test/java/seedu/contax/logic/commands/AppointmentsBetweenCommandTest.java
- src/test/java/seedu/contax/logic/commands/DeleteAppointmentCommandTest.java
- src/test/java/seedu/contax/logic/commands/EditAppointmentCommandTest.java
- src/test/java/seedu/contax/logic/commands/ListAppointmentCommandTest.java
- src/test/java/seedu/contax/logic/parser/AddressBookParserTest.java
- src/test/java/seedu/contax/logic/parser/AppointmentsBetweenCommandParserTest.java
- src/test/java/seedu/contax/model/ModelManagerTest.java
- src/test/java/seedu/contax/model/appointment/DateRangePredicateTest.java
- src/test/java/seedu/contax/testutil/DateInputUtil.java
This PR adds a command to list all appointments within a given date range.
- Closes #121
> Feature - Add Command to List Appointments in Range.

- src/main/java/seedu/contax/logic/commands/EditAppointmentCommand.java
- src/main/java/seedu/contax/logic/commands/ListAppointmentCommand.java
- src/main/java/seedu/contax/logic/parser/AddAppointmentCommandParser.java
- src/main/java/seedu/contax/logic/parser/AppointmentsBetweenCommandParser.java
- src/main/java/seedu/contax/logic/parser/DeleteAppointmentCommandParser.java
- src/main/java/seedu/contax/logic/parser/EditAppointmentCommandParser.java
- src/main/java/seedu/contax/model/AddressBook.java
- src/main/java/seedu/contax/model/Model.java
- src/main/java/seedu/contax/model/ModelManager.java
- src/main/java/seedu/contax/model/ReadOnlyAddressBook.java
- src/main/java/seedu/contax/model/ReadOnlySchedule.java
- src/main/java/seedu/contax/model/Schedule.java
- src/main/java/seedu/contax/model/UserPrefs.java
- src/main/java/seedu/contax/model/appointment/Appointment.java
- src/main/java/seedu/contax/model/appointment/DateRangePredicate.java
- src/main/java/seedu/contax/model/appointment/DisjointAppointmentList.java
- src/main/java/seedu/contax/model/appointment/Duration.java
- src/main/java/seedu/contax/model/appointment/Name.java
- src/main/java/seedu/contax/model/appointment/StartDateTime.java
- src/main/java/seedu/contax/storage/JsonAdaptedAppointment.java
- src/main/java/seedu/contax/storage/JsonScheduleStorage.java
- src/main/java/seedu/contax/storage/JsonSerializableSchedule.java
- src/main/java/seedu/contax/storage/ScheduleStorage.java
- src/test/java/seedu/contax/logic/commands/CommandResultTest.java
- src/test/java/seedu/contax/storage/JsonAdaptedAppointmentTest.java
- src/test/java/seedu/contax/storage/StorageManagerTest.java
This PR mainly focuses on improving coverage and fixing problematic javadoc comments. No major logic changes were made.
- None, code quality enhancement.
> Fix Javadoc Inconsistencies

- src/main/java/seedu/contax/logic/commands/EditTagCommand.java
- src/main/java/seedu/contax/logic/parser/AddTagCommandParser.java
- src/main/java/seedu/contax/logic/parser/AddressBookParser.java
- src/main/java/seedu/contax/logic/parser/CliSyntax.java
- src/main/java/seedu/contax/logic/parser/EditTagCommandParser.java
- src/main/java/seedu/contax/logic/parser/ParserUtil.java
- src/main/java/seedu/contax/model/AddressBook.java
- src/main/java/seedu/contax/model/tag/Name.java
- src/main/java/seedu/contax/model/tag/Tag.java
- src/main/java/seedu/contax/storage/JsonAdaptedTag.java
- src/main/java/seedu/contax/storage/JsonSerializableAddressBook.java
- src/main/java/seedu/contax/ui/PersonCard.java
- src/main/java/seedu/contax/ui/TagCard.java
- src/test/java/seedu/contax/logic/commands/EditTagCommandTest.java
- src/test/java/seedu/contax/logic/parser/AddCommandParserTest.java
- src/test/java/seedu/contax/logic/parser/AddTagCommandParserTest.java
- src/test/java/seedu/contax/logic/parser/AddressBookParserTest.java
- src/test/java/seedu/contax/logic/parser/EditCommandParserTest.java
- src/test/java/seedu/contax/logic/parser/EditTagCommandParserTest.java
- src/test/java/seedu/contax/model/tag/NameTest.java
- src/test/java/seedu/contax/model/tag/TagTest.java
- src/test/java/seedu/contax/testutil/EditTagDescriptorBuilder.java
- src/test/java/seedu/contax/testutil/PersonUtil.java
- src/test/java/seedu/contax/testutil/TagBuilder.java
- src/test/java/seedu/contax/testutil/TagUtil.java
This PR adds the command to allow the user to update a specified tag.
- Closes #116
> Feature - Update Tag

- docs/UserGuide.md
This PR updates the UG to fit the implemented `exportcsv` command format.
Merge this PR after #172 is merged as that PR contains the main functionality.
Issue Ref: #129
> Update UG to fit exportcsv format

- src/main/java/seedu/contax/commons/core/Messages.java
- src/main/java/seedu/contax/logic/Logic.java
- src/main/java/seedu/contax/logic/LogicManager.java
- src/main/java/seedu/contax/logic/commands/DeleteTagCommand.java
- src/main/java/seedu/contax/logic/commands/EditTagCommand.java
- src/main/java/seedu/contax/logic/commands/FindByTagCommand.java
- src/main/java/seedu/contax/logic/commands/ListTagCommand.java
- src/main/java/seedu/contax/logic/parser/AddressBookParser.java
- src/main/java/seedu/contax/logic/parser/FindByTagCommandParser.java
- src/main/java/seedu/contax/model/Model.java
- src/main/java/seedu/contax/model/ModelManager.java
- src/main/java/seedu/contax/model/person/TagNameContainsKeywordsPredicate.java
- src/main/java/seedu/contax/model/tag/NameContainsKeywordsPredicate.java
- src/main/java/seedu/contax/ui/MainWindow.java
- src/test/java/seedu/contax/logic/commands/AddAppointmentCommandTest.java
- src/test/java/seedu/contax/logic/commands/AddCommandTest.java
- src/test/java/seedu/contax/logic/commands/AddTagCommandTest.java
- src/test/java/seedu/contax/logic/commands/DeleteTagCommandTest.java
- src/test/java/seedu/contax/logic/commands/FindByTagCommandTest.java
- src/test/java/seedu/contax/logic/parser/AddressBookParserTest.java
- src/test/java/seedu/contax/logic/parser/FindByTagCommandParserTest.java
- src/test/java/seedu/contax/model/person/TagNameContainsKeywordsPredicateTest.java
- src/test/java/seedu/contax/model/tag/NameContainsKeywordsPredicateTest.java
This PR adds the command to allow the user to find persons who contains a tag matching the specified keyword.
- Closes #127
> Feature - Find Persons by Tag

- src/main/java/seedu/contax/logic/parser/AddAppointmentCommandParser.java
- src/main/java/seedu/contax/logic/parser/AddCommandParser.java
- src/main/java/seedu/contax/logic/parser/AddTagCommandParser.java
- src/main/java/seedu/contax/logic/parser/AppointmentsBetweenCommandParser.java
- src/main/java/seedu/contax/logic/parser/ArgumentMultimap.java
- src/main/java/seedu/contax/logic/parser/FindCommandParser.java
- src/main/java/seedu/contax/logic/parser/ImportCsvParser.java
- src/main/java/seedu/contax/model/util/SearchType.java
- src/test/java/seedu/contax/logic/commands/ExportCsvCommandTest.java
- src/test/java/seedu/contax/logic/parser/AddressBookParserTest.java
- src/test/java/seedu/contax/logic/parser/ArgumentTokenizerTest.java
- src/test/java/seedu/contax/logic/parser/FindCommandParserTest.java
- src/test/java/seedu/contax/logic/parser/ParserUtilTest.java
- src/test/java/seedu/contax/model/util/SearchTypeTest.java
- src/test/java/seedu/contax/storage/CsvManagerTest.java
- This PR fixes bugs in the `FindCommandParser` file, and adds tests to validate that they all work
- Refactor `SearchType` and `FindCommandParser` interactions
- Fixes export tests to use temporary folder instead of a fixed path
None, this is a code quality improvement.
> Fix - Find Command and Improve Coverage

- src/main/java/seedu/contax/commons/core/Messages.java
- src/main/java/seedu/contax/logic/commands/BatchCommand.java
- src/main/java/seedu/contax/logic/commands/RangeCommand.java
- src/main/java/seedu/contax/logic/parser/AddressBookParser.java
- src/main/java/seedu/contax/logic/parser/BatchCommandParser.java
- src/main/java/seedu/contax/logic/parser/CliSyntax.java
- src/main/java/seedu/contax/logic/parser/ParserUtil.java
- src/main/java/seedu/contax/logic/parser/RangeCommandParser.java
- src/test/java/seedu/contax/logic/commands/BatchCommandTest.java
- src/test/java/seedu/contax/logic/parser/AddressBookParserTest.java
- src/test/java/seedu/contax/logic/parser/BatchCommandParserTest.java
- src/test/java/seedu/contax/logic/parser/ParserUtilTest.java
This PR create feature of batch command use regex and related test cases
> more test cases and batch command by equals

- src/main/java/seedu/contax/logic/commands/BatchCommand.java
- src/main/java/seedu/contax/logic/parser/BatchCommandParser.java
- src/main/java/seedu/contax/logic/parser/CliSyntax.java
- src/main/java/seedu/contax/model/util/BatchType.java
- src/test/java/seedu/contax/logic/commands/BatchCommandTest.java
- src/test/java/seedu/contax/logic/commands/ChainCommandTest.java
- src/test/java/seedu/contax/logic/parser/BatchCommandParserTest.java
This PR adds feature of more prefix with ^ and $ to check user input in batch command
Pending for testcases
- closes #225
> Update feature for start and end with

- src/main/java/seedu/contax/MainApp.java
This PR bumps internal version number for v1.3 release
> Bump version for v1.3 release

- src/main/java/seedu/contax/model/CompositeTemporalObservableList.java
- src/main/resources/view/DarkTheme.css
- src/main/resources/view/MainWindow.fxml
This PR resolves a few bugs related to the UI that were previously reported, and also attempts to improve the styling of the UI tabs to be more consistent with the rest of the UI.
**Feel free to suggest / feedback on the UI changes**.
- Closes #227 
- Closes #228
> Bug-Fix - UI Initialization and Styling

- docs/UserGuide.md
This PR updates the user guide for the overall flow and refines the sections related to appointments.
None, this is an improvement as opposed to a fix.
> Documentation - Update Overall User Guide and Appointment Commands

- src/main/java/seedu/contax/logic/commands/EditPriorityCommand.java
This PR is minor changes on command word only
> Change priority command word

- src/main/java/seedu/contax/logic/commands/ClearCommand.java
- src/test/java/seedu/contax/logic/commands/ClearCommandTest.java
This PR updates the clear command to also clear the schedule.
- Closes #242
> Bug Fix - Clear Command Clearing Schedule

- src/main/java/seedu/contax/MainApp.java
This PR bumps the internal version number to 1.3.1 to prepare release of `v1.3b`
> Release - 1.3b internal version bump

- docs/DeveloperGuide.md
- docs/UserGuide.md
- src/main/java/seedu/contax/ui/HelpWindow.java
This PR only adds:
- findappt to UG 
- Onboarding to the glossary in DG.
> Small update to DG and UG 

- docs/DeveloperGuide.md
This PR fixed 2 small typographical errors in the DG.
None, this is a minor bug fix.
> Fix typographical errors in DG

- src/main/java/seedu/contax/logic/commands/FindAppointmentCommand.java
- src/main/java/seedu/contax/logic/commands/FindPersonCommand.java
This PR fixes 2 bugs discovered during manual testing
- Appointment slots not clearing after findappt command is executed
- Command usage for `findperson` is outdated
> Bug Fix - Appointment Slot Clearing and Find Person Usage

- docs/team/dandaandaaaaaan.md
This PR updates my PPP with more recent contributions.
I think this will change for sure especially once we synchronise the format of how we want to write the content of the PPP (for example, possibly include links to PRs, etc.), so good chance I will update this before it is ready to be merged. 
Live version can be seen [here](https://dandaandaaaaaan.github.io/tp/team/dandaandaaaaaan.html)
> Update PPP - Daniel

- docs/UserGuide.md
- src/main/java/seedu/contax/ui/onboarding/OnboardingStoryManager.java
- src/main/java/seedu/contax/ui/onboarding/Overlay.java
This PR fixes the onboarding related bugs that are raised in the PE-D.
Bug fixes as follows:
- Fix any where to anywhere - #274
- Fix user can click anywhere now (but cannot interact with person list) - #278
- Specify keyword ordering is only fixed for Onboarding in UG - #279.
- Remove inconsistent step as in issue - #280.
- 
- Closes #274
- Closes #278
- Closes #279
- Closes #280
> Bug Fix - Onboarding 

- docs/team/sharpstorm.md
This PR updates the PPP for Zong Han to the latest `v1.3b` milestone.
None
> Update PPP - Zong Han

- docs/team/dandaandaaaaaan.md
- src/main/java/seedu/contax/logic/commands/ExportCsvCommand.java
- src/main/java/seedu/contax/logic/commands/ImportCsvCommand.java
- src/main/java/seedu/contax/logic/parser/ImportCsvParser.java
- src/main/java/seedu/contax/model/IndexedCsvFile.java
- src/main/java/seedu/contax/storage/CsvManager.java
- src/main/java/seedu/contax/storage/JsonSerializableAddressBook.java
- src/main/java/seedu/contax/ui/ResultDisplay.java
- src/main/java/seedu/contax/ui/TextStyleHelper.java
This PR mostly cleans up the javadocs for the files that I wrote. Also changed one of the `Logger` usages to use `Logger.info` rather than `Logger.fine`
I don't really remember what I wrote so let me know if I missed any files
> Cleanup for my parts

- src/main/java/seedu/contax/MainApp.java
- src/main/java/seedu/contax/logic/parser/AddressBookParser.java
- src/main/java/seedu/contax/logic/parser/ParserUtil.java
This PR modifies `AddressBookParser` and `MainApp` to adhere to the 30 line per method limit.
None
> Refactor Common Classes to Adhere to 30 Line Limit

- docs/team/wei-xinn.md
> Update PPP - Wei Xin

- src/main/java/seedu/contax/storage/JsonSerializableAddressBook.java
This PR reduces the forgiving json import method to below 30 lines
> Cleanup - Reduce forgiving json to 30 lines

- docs/team/hanjiyao.md
> Update PPP - Han Jiyao

- docs/UserGuide.md
- src/main/java/seedu/contax/ui/onboarding/OnboardingPrompt.java
- src/main/java/seedu/contax/ui/onboarding/OnboardingStoryManager.java
- src/main/resources/view/HelpWindow.fxml
- src/main/resources/view/onboarding/OnboardingPrompt.fxml
This PR fixes the sizing issue for the onboarding window on linux.
> Fix sizing bug

- src/main/java/seedu/contax/logic/parser/AddressBookParser.java
I am not quite sure why response is not picking up the authorship comment for @Wei-Xinn and @HanJiyao. This is a fix to attempt a fix.
> Fix Code Authorship Case Sensitivity

- src/main/java/seedu/contax/logic/commands/BatchCommand.java
This PR changes to reverse order to bathc command
> Bug Fix - batch reverse order

- docs/DeveloperGuide.md
This PR adds the effort component for the DG
> Add effort component to DG

- src/main/java/seedu/contax/logic/commands/BatchCommand.java
- src/main/java/seedu/contax/logic/commands/RangeCommand.java
- src/main/java/seedu/contax/logic/parser/ParserUtil.java
- src/test/java/seedu/contax/logic/commands/RangeCommandTest.java
This PR Fix range command format and test cases
> Code reformat and test coverage improvement

- src/main/java/seedu/contax/MainApp.java
This PR bumps internal version number in preparation for v1.4 release
> Bump internal version number for v1.4
